/* AUTHENTICATION TYPES */
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';

export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_ME_SUCCESS = 'AUTH_ME_SUCCESS';
export const AUTH_ME_FAILURE = 'AUTH_ME_FAILURE';

export const AUTH_FOROGOT_PASSWORD_SUCCESS = 'AUTH_FOROGOT_PASSWORD_SUCCESS';
export const AUTH_FOROGOT_PASSWORD_FAILURE = 'AUTH_FOROGOT_PASSWORD_FAILURE';

export const AUTH_UPDATE_USER_SUCCESS = 'AUTH_UPDATE_USER_SUCCESS';
export const AUTH_UPDATE_USER_FAILURE = 'AUTH_UPDATE_USER_FAILURE';

export const AUTH_RESET_PASSWORD_SUCCESS = 'AUTH_RESET_PASSWORD_SUCCESS';
export const AUTH_RESET_PASSWORD_FAILURE = 'AUTH_RESET_PASSWORD_FAILURE';

export const AUTH_UPDATE_PASSWORD_SUCCESS = 'AUTH_UPDATE_PASSWORD_SUCCESS';
export const AUTH_UPDATE_PASSWORD_FAILURE = 'AUTH_UPDATE_PASSWORD_FAILURE';

export const AUTH_USER_LOADED = 'AUTH_USER_LOADED';
export const AUTH_ERR = 'AUTH_ERR';

/* MAP TYPES */
export const MAP_CREATE_SUCCESS = 'MAP_CREATE_SUCCESS';
export const MAP_CREATE_FAILURE = 'MAP_CREATE_FAILURE';

export const MAP_USER_GET_SUCCESS = 'MAP_USER_GET_SUCCESS';
export const MAP_USER_GET_FAILURE = 'MAP_USER_GET_FAILURE';

export const MAP_GET_SINGLE_SUCCESS = 'MAP_GET_SINGLE_SUCCESS';
export const MAP_GET_SINGLE_FAILURE = 'MAP_GET_SINGLE_FAILURE';

export const MAP_DELETE_SINGLE_SUCCESS = 'MAP_DELETE_SINGLE_SUCCESS';
export const MAP_DELETE_SINGLE_FAILURE = 'MAP_DELETE_SINGLE_FAILURE';

export const MAP_CREATE_RESET = 'MAP_CREATE_RESET';

export const MAP_IS_LOADING = 'MAP_IS_LOADING';

/* LAYER TYPES */
export const LAYER_CREATE_SUCCESS = 'LAYER_CREATE_SUCCESS';
export const LAYER_CREATE_FAILURE = 'LAYER_CREATE_FAILURE';

export const LAYER_GET_BY_MAP_SUCCESS = 'LAYER_GET_BY_MAP_SUCCESS';
export const LAYER_GET_BY_MAP_FAILURE = 'LAYER_GET_BY_MAP_FAILURE';

export const LAYER_UPDATE_SUCCESS = 'LAYER_UPDATE_SUCCESS';
export const LAYER_UPDATE_FAILURE = 'LAYER_UPDATE_FAILURE';

export const LAYER_DELETE_SUCCESS = 'LAYER_DELETE_SUCCSS';
export const LAYER_DELETE_FAILURE = 'LAYER_DELETE_FAILURE';

/* NODE TYPES */
export const NODE_CREATE_SUCCESS = 'NODE_CREATE_SUCCESS';
export const NODE_CREATE_FAILURE = 'NODE_CREATE_FAILURE';

export const NODE_GET_BY_MAP_SUCCESS = 'NODE_GET_BY_MAP_SUCCESS';
export const NODE_GET_BY_MAP_FAILURE = 'NODE_GET_BY_MAP_FAILURE';

export const NODE_UPDATE_SUCCESS = 'NODE_UPDATE_SUCCESS';
export const NODE_UPDATE_FAILURE = 'NODE_UPDATE_FAILURE';

export const NODE_DELETE_SUCCESS = 'NODE_DELETE_SUCCSS';
export const NODE_DELETE_FAILURE = 'NODE_DELETE_FAILURE';

/* LAYERGRID TYPES  */
export const LAYERGRID_SET_LAYER = 'LAYERGRID_SET_LAYER';
export const LAYERGRID_SET_WORKING_LAYER = 'LAYERGRID_SET_WORKING_LAYER';
export const LAYERGRID_DELETE_LAYER_CHECK = 'LAYERGRID_DELETE_LAYER_CHECK';
export const LAYERGRID_UNSET_LAYER = 'LAYERGRID_UNSET_LAYER';
export const LAYERGRID_SET_WORKING_MAP_ID = 'LAYERGRID_SET_WORKING_MAP_ID';
export const LAYERGRID_CLEAR_CONTEXT = 'LAYERGRID_CLEAR_CONTEXT';

/* MAPMODE TYPES */
export const MAPMODE_TOGGLE_MODE = 'MAPMODE_TOGGLE_MODE';
export const MAPMODE_SET_EDIT = 'MAPMODE_SET_EDIT';
export const MAPMODE_SET_VIEW = 'MAPMODE_SET_VIEW';

/* TOOLBAR TYPES */
export const TOOLBAR_SET_TOOL = 'TOOLBAR_SET_TOOL';
export const TOOLBAR_CLEAR_CONTEXT = 'TOOLBAR_CLEAR_CONTEXT';

export const TOOLBAR_ADD = 'TOOLBAR_ADD';
export const TOOLBAR_REMOVE = 'TOOLBAR_REMOVE';
export const TOOLBAR_MOVE = 'TOOLBAR_MOVE';
export const TOOLBAR_SELECT = 'TOOLBAR_SELECT';

/* INFOBAR TYPES */
export const INFOBAR_SET_SELECTED = 'INFOBAR_SET_SELECTED';
export const INFOBAR_SET_EDITING_MODE = 'INFOBAR_SET_EDITING_MODE';
export const INFOBAR_SET_VIEW_MODE = 'INFOBAR_SET_VIEW_MODE';
export const INFOBAR_CLEAR_CONTEXT = 'INFOBAR_CLEAR_CONTEXT';

/* CONUSERS TYPES */
export const CONUSERS_SET_CONN_POS = 'CONUSERS_SET_CONN_POS';
export const CONUSERS_REMOVE_CONN = 'CONUSERS_REMOVE_CONN';
export const CONUSERS_CLEAR_CONTEXT = 'CONUSERS_CLEAR_CONTEXT';
